### ISSUE TITLE
Crashes consistently at around 2.5k games and 1 GB ram usage.

### ISSUE THREAD

**Issue by kyle7575** [boppreh/steamgrid#50]
I'm fine with it using more resources to finish but it always crashes at 1.1 GB ram usage 

https://i.imgur.com/Z2ARYJl.png
(error i get.)

Any help would be great.

**Comment by TheRelentless** [comment]
I am getting this with the latest version.  Never got it before.

**Comment by Lucki** [comment]
The `png: invalid format: chunk out of order` looks suspicious. Did this start at a specific picture? Can you view them in the grid folder and/or in the backup folder?

**Comment by CriticalCid** [comment]
I get the same error but without the `png: invalid format: chunk out of order` message. I only started to use this program yesterday and tried it multiple times since then but it always crashes for me after a couple of thousand games.

> Processing The Lone Chameleon (7226/12146)
Hero not found
Logo not found
Banner found from backup
Cover not found
Processing UGT - 1. 3DS Max Modeling - 1.5 (7227/12146)
Banner found from backup
Cover found from backup
Hero found from backup
runtime: out of memory: cannot allocate 19046400-byte block (1654521856 in use)
fatal error: out of memory

> runtime stack:
runtime.throw(0x6f5f49, 0xd)
        c:/go/src/runtime/panic.go:774 +0x64
runtime.largeAlloc(0x122a000, 0x440101, 0x7c6a0000)
        c:/go/src/runtime/malloc.go:1140 +0x108
runtime.mallocgc.func1()
        c:/go/src/runtime/malloc.go:1033 +0x39
runtime.systemstack(0x0)
        c:/go/src/runtime/asm_386.s:399 +0x53
runtime.mstart()
        c:/go/src/runtime/proc.go:1146

> goroutine 1 [running]:
runtime.systemstack_switch()
        c:/go/src/runtime/asm_386.s:360 fp=0x118791ac sp=0x118791a8 pc=0x44eac0
runtime.mallocgc(0x122a000, 0x6aaa20, 0x1, 0x7c6a0000)
        c:/go/src/runtime/malloc.go:1032 +0x684 fp=0x11879200 sp=0x118791ac pc=0x40a1f4
runtime.makeslice(0x6aaa20, 0x122a0, 0x122a0, 0x7c6a0000)
        c:/go/src/runtime/slice.go:49 +0x4f fp=0x11879214 sp=0x11879200 pc=0x43bddf
image/jpeg.(*decoder).processSOS(0x36334a00, 0xa, 0x2, 0x80)
        c:/go/src/image/jpeg/scan.go:156 +0x57f fp=0x118793f4 sp=0x11879214 pc=0x62467f
image/jpeg.(*decoder).decode(0x36334a00, 0x75e400, 0x11818450, 0x407f00, 0x6b14c0, 0x6e7280, 0x70d000, 0x75e400)
        c:/go/src/image/jpeg/reader.go:630 +0x29c fp=0x11879418 sp=0x118793f4 pc=0x622c3c
image/jpeg.Decode(0x75e400, 0x11818450, 0x11818450, 0x75e400, 0x11818450, 0x2)
        c:/go/src/image/jpeg/reader.go:779 +0x44 fp=0x1187943c sp=0x11879418 pc=0x623a64
image.Decode(0x75e440, 0x118de140, 0x118de120, 0x1, 0x1, 0x0, 0x75eea0, 0x75a9c8)
        c:/go/src/image/format.go:93 +0xb1 fp=0x118794b8 sp=0x1187943c pc=0x4f7c21
main.ApplyOverlay(0x12e4fe50, 0x118ba280, 0x11884140, 0x7, 0x7, 0x2, 0x2)
        C:/Users/BoppreH/Desktop/source/go/src/github.com/boppreh/steamgrid/overlays.go:86 +0xfe6 fp=0x11879634 sp=0x118794b8 pc=0x6686e6
main.startApplication()
        C:/Users/BoppreH/Desktop/source/go/src/github.com/boppreh/steamgrid/steamgrid.go:213 +0x13f1 fp=0x11879fa0 sp=0x11879634 pc=0x669d51
main.main()
        C:/Users/BoppreH/Desktop/source/go/src/github.com/boppreh/steamgrid/steamgrid.go:27 +0x41 fp=0x11879fb0 sp=0x11879fa0 pc=0x668931
runtime.main()
        c:/go/src/runtime/proc.go:203 +0x1e6 fp=0x11879ff0 sp=0x11879fb0 pc=0x42c806
runtime.goexit()
        c:/go/src/runtime/asm_386.s:1325 +0x1 fp=0x11879ff4 sp=0x11879ff0 pc=0x4503d1

> goroutine 147 [IO wait]:
internal/poll.runtime_pollWait(0x1388f58, 0x72, 0x75f4c0)
        c:/go/src/runtime/netpoll.go:184 +0x4b
internal/poll.(*pollDesc).wait(0x1187ebfc, 0x72, 0x8ed100, 0x0, 0x0)
        c:/go/src/internal/poll/fd_poll_runtime.go:87 +0x37
internal/poll.(*ioSrv).ExecIO(0x926fe4, 0x1187eb14, 0x70d0b8, 0xd74, 0x10, 0x0)
        c:/go/src/internal/poll/fd_windows.go:228 +0xef
internal/poll.(*FD).Read(0x1187eb00, 0x1187a000, 0xd81, 0xd81, 0x0, 0x0, 0x0)
        c:/go/src/internal/poll/fd_windows.go:527 +0x10a
net.(*netFD).Read(0x1187eb00, 0x1187a000, 0xd81, 0xd81, 0x1, 0x1575249, 0x14a)
        c:/go/src/net/fd_windows.go:152 +0x3f
net.(*conn).Read(0x118060f0, 0x1187a000, 0xd81, 0xd81, 0x0, 0x0, 0x0)
        c:/go/src/net/net.go:184 +0x56
crypto/tls.(*atLeastReader).Read(0x1301f490, 0x1187a000, 0xd81, 0xd81, 0x0, 0x926d08, 0x117c0c40)
        c:/go/src/crypto/tls/conn.go:780 +0x61
bytes.(*Buffer).ReadFrom(0x1189c360, 0x75e540, 0x1301f490, 0x136628c0, 0x407fa9, 0x6b14c0, 0x6e90c0)
        c:/go/src/bytes/buffer.go:204 +0x95
crypto/tls.(*Conn).readFromUntil(0x1189c200, 0x117c0c40, 0x118060f0, 0x5, 0x118060f0, 0x4c)
        c:/go/src/crypto/tls/conn.go:802 +0xcb
crypto/tls.(*Conn).readRecordOrCCS(0x1189c200, 0x0, 0x0, 0xd10f225c)
        c:/go/src/crypto/tls/conn.go:609 +0x114
crypto/tls.(*Conn).readRecord(...)
        c:/go/src/crypto/tls/conn.go:577
crypto/tls.(*Conn).Read(0x1189c200, 0x118dc000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        c:/go/src/crypto/tls/conn.go:1255 +0x136
bufio.(*Reader).Read(0x118978f0, 0x118a2220, 0x9, 0x9, 0x0, 0x0, 0x11875e3c)
        c:/go/src/bufio/bufio.go:226 +0x1f6
io.ReadAtLeast(0x75e400, 0x118978f0, 0x118a2220, 0x9, 0x9, 0x9, 0x11875e84, 0x75e601, 0x1184c018)
        c:/go/src/io/io.go:310 +0x74
io.ReadFull(...)
        c:/go/src/io/io.go:329
net/http.http2readFrameHeader(0x118a2220, 0x9, 0x9, 0x75e400, 0x118978f0, 0x0, 0x0, 0x0, 0x118df740, 0x0)
        c:/go/src/net/http/h2_bundle.go:1477 +0x6e
net/http.(*http2Framer).ReadFrame(0x118a2200, 0x118df740, 0x0, 0x0, 0x0)
        c:/go/src/net/http/h2_bundle.go:1735 +0x76
net/http.(*http2clientConnReadLoop).run(0x11875fdc, 0x121b2f60, 0x58ff74)
        c:/go/src/net/http/h2_bundle.go:8175 +0x69
net/http.(*http2ClientConn).readLoop(0x13666a80)
        c:/go/src/net/http/h2_bundle.go:8103 +0x6d
created by net/http.(*http2Transport).newClientConn
        c:/go/src/net/http/h2_bundle.go:7162 +0x572

> goroutine 85 [IO wait]:
internal/poll.runtime_pollWait(0x1388e50, 0x72, 0x75f4c0)
        c:/go/src/runtime/netpoll.go:184 +0x4b
internal/poll.(*pollDesc).wait(0x1187f01c, 0x72, 0x8ed100, 0x0, 0x0)
        c:/go/src/internal/poll/fd_poll_runtime.go:87 +0x37
internal/poll.(*ioSrv).ExecIO(0x926fe4, 0x1187ef34, 0x70d0b8, 0x92f40cb5, 0x1197c13a, 0x7378cff)
        c:/go/src/internal/poll/fd_windows.go:228 +0xef
internal/poll.(*FD).Read(0x1187ef20, 0x1197c000, 0xee0, 0xee0, 0x0, 0x0, 0x0)
        c:/go/src/internal/poll/fd_windows.go:527 +0x10a
net.(*netFD).Read(0x1187ef20, 0x1197c000, 0xee0, 0xee0, 0x0, 0x1400003, 0x4)
        c:/go/src/net/fd_windows.go:152 +0x3f
net.(*conn).Read(0x1195c000, 0x1197c000, 0xee0, 0xee0, 0x0, 0x0, 0x0)
        c:/go/src/net/net.go:184 +0x56
crypto/tls.(*atLeastReader).Read(0x11900030, 0x1197c000, 0xee0, 0xee0, 0x0, 0x926d08, 0x117c0c40)
        c:/go/src/crypto/tls/conn.go:780 +0x61
bytes.(*Buffer).ReadFrom(0x1195e160, 0x75e540, 0x11900030, 0x1197c13a, 0x407fa9, 0x6b14c0, 0x6e90c0)
        c:/go/src/bytes/buffer.go:204 +0x95
crypto/tls.(*Conn).readFromUntil(0x1195e000, 0x117c0c40, 0x1195c000, 0x5, 0x1195c000, 0x9)
        c:/go/src/crypto/tls/conn.go:802 +0xcb
crypto/tls.(*Conn).readRecordOrCCS(0x1195e000, 0x0, 0x0, 0x11839dc4)
        c:/go/src/crypto/tls/conn.go:609 +0x114
crypto/tls.(*Conn).readRecord(...)
        c:/go/src/crypto/tls/conn.go:577
crypto/tls.(*Conn).Read(0x1195e000, 0x119b8000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        c:/go/src/crypto/tls/conn.go:1255 +0x136
bufio.(*Reader).Read(0x119b4000, 0x119be020, 0x9, 0x9, 0x0, 0x0, 0x11839e3c)
        c:/go/src/bufio/bufio.go:226 +0x1f6
io.ReadAtLeast(0x75e400, 0x119b4000, 0x119be020, 0x9, 0x9, 0x9, 0x11839e84, 0x75e601, 0x1184c018)
        c:/go/src/io/io.go:310 +0x74
io.ReadFull(...)
        c:/go/src/io/io.go:329
net/http.http2readFrameHeader(0x119be020, 0x9, 0x9, 0x75e400, 0x119b4000, 0x0, 0x0, 0x0, 0x68944120, 0x0)
        c:/go/src/net/http/h2_bundle.go:1477 +0x6e
net/http.(*http2Framer).ReadFrame(0x119be000, 0x68944120, 0x0, 0x0, 0x0)
        c:/go/src/net/http/h2_bundle.go:1735 +0x76
net/http.(*http2clientConnReadLoop).run(0x11839fdc, 0x121b3f60, 0x58ff74)
        c:/go/src/net/http/h2_bundle.go:8175 +0x69
net/http.(*http2ClientConn).readLoop(0x13658540)
        c:/go/src/net/http/h2_bundle.go:8103 +0x6d
created by net/http.(*http2Transport).newClientConn
        c:/go/src/net/http/h2_bundle.go:7162 +0x572

> goroutine 25637 [IO wait]:
internal/poll.runtime_pollWait(0x1388fdc, 0x72, 0x75f4c0)
        c:/go/src/runtime/netpoll.go:184 +0x4b
internal/poll.(*pollDesc).wait(0x68957ddc, 0x72, 0x8ed100, 0x0, 0x0)
        c:/go/src/internal/poll/fd_poll_runtime.go:87 +0x37
internal/poll.(*ioSrv).ExecIO(0x926fe4, 0x68957cf4, 0x70d0b8, 0x7778ef6f, 0x134d0557, 0x1695)
        c:/go/src/internal/poll/fd_windows.go:228 +0xef
internal/poll.(*FD).Read(0x68957ce0, 0x134ce000, 0x2730, 0x2730, 0x0, 0x0, 0x0)
        c:/go/src/internal/poll/fd_windows.go:527 +0x10a
net.(*netFD).Read(0x68957ce0, 0x134ce000, 0x2730, 0x2730, 0x1, 0x157516e, 0x6f)
        c:/go/src/net/fd_windows.go:152 +0x3f
net.(*conn).Read(0x12e62298, 0x134ce000, 0x2730, 0x2730, 0x0, 0x0, 0x0)
        c:/go/src/net/net.go:184 +0x56
crypto/tls.(*atLeastReader).Read(0x1301e6e0, 0x134ce000, 0x2730, 0x2730, 0x0, 0x926d08, 0x117c0c40)
        c:/go/src/crypto/tls/conn.go:780 +0x61
bytes.(*Buffer).ReadFrom(0x1195e760, 0x75e540, 0x1301e6e0, 0x134d0557, 0x407fa9, 0x6b14c0, 0x6e90c0)
        c:/go/src/bytes/buffer.go:204 +0x95
crypto/tls.(*Conn).readFromUntil(0x1195e600, 0x117c0c40, 0x12e62298, 0x5, 0x12e62298, 0x9)
        c:/go/src/crypto/tls/conn.go:802 +0xcb
crypto/tls.(*Conn).readRecordOrCCS(0x1195e600, 0x0, 0x0, 0xfc9c9730)
        c:/go/src/crypto/tls/conn.go:609 +0x114
crypto/tls.(*Conn).readRecord(...)
        c:/go/src/crypto/tls/conn.go:577
crypto/tls.(*Conn).Read(0x1195e600, 0x697e9000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        c:/go/src/crypto/tls/conn.go:1255 +0x136
bufio.(*Reader).Read(0x11902a50, 0x119be120, 0x9, 0x9, 0x0, 0x0, 0x11951e3c)
        c:/go/src/bufio/bufio.go:226 +0x1f6
io.ReadAtLeast(0x75e400, 0x11902a50, 0x119be120, 0x9, 0x9, 0x9, 0x11951e84, 0x75e601, 0x1184c018)
        c:/go/src/io/io.go:310 +0x74
io.ReadFull(...)
        c:/go/src/io/io.go:329
net/http.http2readFrameHeader(0x119be120, 0x9, 0x9, 0x75e400, 0x11902a50, 0x0, 0x0, 0x0, 0x1197a7c0, 0x0)
        c:/go/src/net/http/h2_bundle.go:1477 +0x6e
net/http.(*http2Framer).ReadFrame(0x119be100, 0x1197a7c0, 0x0, 0x0, 0x0)
        c:/go/src/net/http/h2_bundle.go:1735 +0x76
net/http.(*http2clientConnReadLoop).run(0x11951fdc, 0x15ef7f60, 0x58ff74)
        c:/go/src/net/http/h2_bundle.go:8175 +0x69
net/http.(*http2ClientConn).readLoop(0x4e0fc1c0)
        c:/go/src/net/http/h2_bundle.go:8103 +0x6d
created by net/http.(*http2Transport).newClientConn
        c:/go/src/net/http/h2_bundle.go:7162 +0x572

> goroutine 22660 [IO wait]:
internal/poll.runtime_pollWait(0x1388ed4, 0x72, 0x75f4c0)
        c:/go/src/runtime/netpoll.go:184 +0x4b
internal/poll.(*pollDesc).wait(0x1187e7dc, 0x72, 0x8ed100, 0x0, 0x0)
        c:/go/src/internal/poll/fd_poll_runtime.go:87 +0x37
internal/poll.(*ioSrv).ExecIO(0x926fe4, 0x1187e6f4, 0x70d0b8, 0xa579e33f, 0x2d2d3005, 0x0)
        c:/go/src/internal/poll/fd_windows.go:228 +0xef
internal/poll.(*FD).Read(0x1187e6e0, 0x2d2d3000, 0xdcd, 0xdcd, 0x0, 0x0, 0x0)
        c:/go/src/internal/poll/fd_windows.go:527 +0x10a
net.(*netFD).Read(0x1187e6e0, 0x2d2d3000, 0xdcd, 0xdcd, 0x1, 0x1575270, 0x171)
        c:/go/src/net/fd_windows.go:152 +0x3f
net.(*conn).Read(0x1184c790, 0x2d2d3000, 0xdcd, 0xdcd, 0x0, 0x0, 0x0)
        c:/go/src/net/net.go:184 +0x56
crypto/tls.(*atLeastReader).Read(0x1301f700, 0x2d2d3000, 0xdcd, 0xdcd, 0x0, 0x926d08, 0x117c0c40)
        c:/go/src/crypto/tls/conn.go:780 +0x61
bytes.(*Buffer).ReadFrom(0x1195e360, 0x75e540, 0x1301f700, 0x2d2d3005, 0x407fa9, 0x6b14c0, 0x6e90c0)
        c:/go/src/bytes/buffer.go:204 +0x95
crypto/tls.(*Conn).readFromUntil(0x1195e200, 0x117c0c40, 0x1184c790, 0x5, 0x1184c790, 0x9)
        c:/go/src/crypto/tls/conn.go:802 +0xcb
crypto/tls.(*Conn).readRecordOrCCS(0x1195e200, 0x0, 0x0, 0xe931ae2c)
        c:/go/src/crypto/tls/conn.go:609 +0x114
crypto/tls.(*Conn).readRecord(...)
        c:/go/src/crypto/tls/conn.go:577
crypto/tls.(*Conn).Read(0x1195e200, 0x1a18d000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        c:/go/src/crypto/tls/conn.go:1255 +0x136
bufio.(*Reader).Read(0x11818960, 0x118a22a0, 0x9, 0x9, 0x0, 0x0, 0x1194fe3c)
        c:/go/src/bufio/bufio.go:226 +0x1f6
io.ReadAtLeast(0x75e400, 0x11818960, 0x118a22a0, 0x9, 0x9, 0x9, 0x1194fe84, 0x75e601, 0x1184c018)
        c:/go/src/io/io.go:310 +0x74
io.ReadFull(...)
        c:/go/src/io/io.go:329
net/http.http2readFrameHeader(0x118a22a0, 0x9, 0x9, 0x75e400, 0x11818960, 0x0, 0x0, 0x0, 0x118dfbe0, 0x0)
        c:/go/src/net/http/h2_bundle.go:1477 +0x6e
net/http.(*http2Framer).ReadFrame(0x118a2280, 0x118dfbe0, 0x0, 0x0, 0x0)
        c:/go/src/net/http/h2_bundle.go:1735 +0x76
net/http.(*http2clientConnReadLoop).run(0x1194ffdc, 0x60ddf2, 0x70d22c)
        c:/go/src/net/http/h2_bundle.go:8175 +0x69
net/http.(*http2ClientConn).readLoop(0x1b8ebea0)
        c:/go/src/net/http/h2_bundle.go:8103 +0x6d
created by net/http.(*http2Transport).newClientConn
        c:/go/src/net/http/h2_bundle.go:7162 +0x572

**Comment by DoLLo73** [comment]
Same problem here with the latest version and 32GB of ram.
It crash when it reach about 1.5GB of occupation.

**Comment by drguildo** [comment]
I got the out of memory out without the PNG error.

[steamgrid out of memory.txt](https://github.com/boppreh/steamgrid/files/8310943/steamgrid.out.of.memory.txt)
